# Generated by Django 4.2.29 on 2026-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='设备类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'db_table': 'equipment_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_no', models.CharField(default=equipment.models.generate_equipment_no, max_length=50, unique=True, verbose_name='设备编号')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('equipment_image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='设备图片')),
                ('specification', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备规格')),
                ('quantity', models.IntegerField(default=1, verbose_name='设备数量')),
                ('location', models.CharField(max_length=200, verbose_name='设备位置')),
                ('status', models.CharField(default='正常', max_length=50, verbose_name='设备状态')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '公共设备',
                'verbose_name_plural': '公共设备',
                'db_table': 'equipment',
                'ordering': ['-publish_time'],
            },
        ),
    ]
