# Generated by Django 4.2.29 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='设备图片'),
        ),
    ]
