# Generated by Django 4.2.29 on 2026-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_equipment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '设备类型', 'verbose_name_plural': '设备类型'},
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型编码'),
        ),
    ]
