# Generated by Django 4.2.29 on 2026-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipmenttype_options_equipmenttype_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='fault_count',
            field=models.IntegerField(default=0, verbose_name='故障数量'),
        ),
    ]
