# Generated by Django 4.2.29 on 2026-04-03 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_equipment_fault_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='EquipmentTypeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='申请类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('applicant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='申请人姓名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_reply', models.TextField(blank=True, null=True, verbose_name='审核回复')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_type_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '设备类型申请',
                'verbose_name_plural': '设备类型申请',
                'db_table': 'equipment_type_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
