# Generated by Django 4.2.29 on 2026-04-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_add_equipment_type_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='院区名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='院区编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '院区',
                'verbose_name_plural': '院区',
                'db_table': 'campus',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_reportable',
            field=models.BooleanField(default=True, verbose_name='可报修'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='房间号'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('water_electric', '水电'), ('door_window', '门窗'), ('multimedia', '教学多媒体'), ('network', '网络'), ('dorm_furniture', '宿舍家具'), ('other', '其他')], default='other', max_length=30, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='equipmenttyperequest',
            name='category',
            field=models.CharField(default='other', max_length=30, verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='楼栋名称')),
                ('code', models.CharField(max_length=50, verbose_name='楼栋编码')),
                ('floor_count', models.IntegerField(default=1, verbose_name='楼层数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='equipment.campus', verbose_name='院区')),
            ],
            options={
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
                'db_table': 'building',
                'ordering': ['campus__id', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.building', verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.campus', verbose_name='院区'),
        ),
    ]
