# Generated by Django 4.2.29 on 2026-04-03 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_full_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='楼层号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='楼层名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '楼层',
                'verbose_name_plural': '楼层',
                'ordering': ['floor_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '楼栋', 'verbose_name_plural': '楼栋'},
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('teaching', '教学楼'), ('dormitory', '宿舍楼'), ('office', '办公楼'), ('lab', '实验楼'), ('library', '图书馆'), ('canteen', '食堂'), ('gym', '体育馆'), ('other', '其他')], default='other', max_length=50, verbose_name='楼栋类型'),
        ),
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='equipment.campus', verbose_name='所属院区'),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='楼栋编码'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floor_count',
            field=models.IntegerField(default=6, verbose_name='楼层总数'),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='房间号')),
                ('name', models.CharField(default='', max_length=100, verbose_name='房间名称')),
                ('room_type', models.CharField(choices=[('classroom', '教室'), ('office', '办公室'), ('lab', '实验室'), ('dorm', '宿舍'), ('meeting', '会议室'), ('restroom', '卫生间'), ('corridor', '走廊/大厅'), ('storage', '仓库'), ('other', '其他')], default='other', max_length=50, verbose_name='房间类型')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='容量(人)')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='面积(m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='equipment.floor', verbose_name='所属楼层')),
            ],
            options={
                'verbose_name': '房间/空间',
                'verbose_name_plural': '房间/空间',
                'ordering': ['room_number'],
                'unique_together': {('floor', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='equipment.building', verbose_name='所属楼栋'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.floor', verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.room', verbose_name='房间/空间'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'floor_number')},
        ),
    ]
