# Generated by Django 4.2.29 on 2026-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_add_floor_room_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='floor_count',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='area',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='其他', max_length=50, verbose_name='楼栋类型'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('water_electric', '水电设施'), ('door_window', '门窗设施'), ('multimedia', '教学多媒体'), ('network', '网络通信设备'), ('dorm_furniture', '宿舍家具'), ('security', '监控安防设备'), ('lab', '实验仪器设备'), ('sports', '体育健身器材'), ('canteen', '餐饮厨房设备'), ('other', '其他')], default='other', max_length=30, verbose_name='分类'),
        ),
    ]
