# Generated by Django 4.2.29 on 2026-04-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_simplify_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['id'], 'verbose_name': '楼栋', 'verbose_name_plural': '楼栋'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building__id', 'floor_number'], 'verbose_name': '楼层', 'verbose_name_plural': '楼层'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='building',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='building',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='floor',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='equipment.campus', verbose_name='所属院区'),
        ),
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.AlterModelTable(
            name='floor',
            table='floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
