# Generated by Django 4.2.29 on 2026-04-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipmenttyperequest',
            name='category',
        ),
    ]
