# Generated by Django 4.2.29 on 2026-04-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_remove_equipmenttype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_image',
            field=models.TextField(blank=True, null=True, verbose_name='设备图片'),
        ),
    ]
