# Generated by Django 4.2.29 on 2026-05-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('equipment', '0013_remove_location_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.room', verbose_name='所在房间'),
        ),
    ]
