# Generated by Django 4.2.29 on 2026-05-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('equipment', '0014_add_room_to_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.building', verbose_name='所在楼栋'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.floor', verbose_name='所在楼层'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('故障', '故障')], default='正常', max_length=50, verbose_name='设备状态'),
        ),
    ]
