# Generated by Django 4.2.29 on 2026-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_split_quantity_and_assign_sequence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['building'], name='idx_equip_building'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='idx_equip_type'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['fault_count'], name='idx_equip_fault'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['building', 'equipment_type'], name='idx_equip_building_type'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_name', 'building'], name='idx_equip_name_building'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='idx_equip_status'),
        ),
    ]
