# Generated by Django 4.2.29 on 2026-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
    ]
