# Generated by Django 4.2.29 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片'),
        ),
    ]
