# Generated by Django 4.2.29 on 2026-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inspection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_no', models.CharField(default=inspection.models.generate_inspection_no, max_length=50, unique=True, verbose_name='巡检单号')),
                ('scene_photo', models.ImageField(blank=True, null=True, upload_to='inspection/', verbose_name='现场照片')),
                ('location', models.CharField(max_length=200, verbose_name='设备位置')),
                ('inspection_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='巡检时间')),
                ('staff_no', models.CharField(max_length=20, verbose_name='巡检人员账号')),
                ('staff_name', models.CharField(max_length=50, verbose_name='巡检人员姓名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='巡检描述')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_reply', models.TextField(blank=True, null=True, verbose_name='审核回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备巡检',
                'verbose_name_plural': '设备巡检',
                'db_table': 'inspection',
                'ordering': ['-inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='检查项目')),
                ('item_status', models.CharField(max_length=50, verbose_name='检查状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inspection.inspection', verbose_name='巡检单')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'db_table': 'inspection_record',
            },
        ),
    ]
