# Generated by Django 4.2.29 on 2026-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.repairstaff', verbose_name='巡检人员'),
        ),
    ]
