# Generated by Django 4.2.29 on 2026-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='scene_photo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='现场照片'),
        ),
    ]
