# Generated by Django 4.2.29 on 2026-04-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('inspection', '0003_alter_inspection_scene_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.building', verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.campus', verbose_name='院区'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.floor', verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location_detail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='详细位置'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='巡检记录'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='result',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=20, verbose_name='巡检结果'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='设备位置'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scene_photo',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='现场照片'),
        ),
    ]
