# Generated by Django 4.2.29 on 2026-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_add_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='scene_photo',
            field=models.TextField(blank=True, null=True, verbose_name='现场照片'),
        ),
    ]
