# Generated by Django 4.2.29 on 2026-04-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_image_textfield'),
        ('inspection', '0005_add_location_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '巡检记录', 'verbose_name_plural': '巡检记录'},
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='equipment_type',
        ),
        migrations.AddField(
            model_name='inspection',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='设备'),
        ),
    ]
