# Generated by Django 4.2.29 on 2026-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_alter_inspectionrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_count',
            field=models.IntegerField(default=1, verbose_name='巡检数量'),
        ),
    ]
