# Generated by Django 4.2.29 on 2026-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_add_inspection_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='idx_inspection_status'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['staff_id'], name='idx_inspection_staff'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-inspection_time'], name='idx_inspection_time'),
        ),
    ]
