# Generated by Django 4.2.29 on 2026-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_inspection_idx_inspection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='equipment_sequence_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='设备序号'),
        ),
    ]
