# Generated by Django 4.2.29 on 2026-04-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repair', '0005_repairorder_repair_start_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_alter_administrator_avatar_alter_repairstaff_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('electrical', '电气设备'), ('mechanical', '机械设备'), ('plumbing', '管道设备'), ('hvac', '暖通设备'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('problem_description', models.TextField(verbose_name='问题描述')),
                ('solution', models.TextField(verbose_name='解决方案')),
                ('equipment_type', models.CharField(blank=True, max_length=100, verbose_name='设备类型')),
                ('keywords', models.CharField(blank=True, help_text='逗号分隔', max_length=500, verbose_name='关键词')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('useful_count', models.IntegerField(default=0, verbose_name='有用次数')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '维修知识库',
                'verbose_name_plural': '维修知识库',
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50, unique=True, verbose_name='备件编号')),
                ('name', models.CharField(max_length=200, verbose_name='备件名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('unit', models.CharField(choices=[('个', '个'), ('件', '件'), ('套', '套'), ('米', '米'), ('公斤', '公斤'), ('升', '升')], default='个', max_length=20, verbose_name='单位')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('max_stock', models.IntegerField(default=100, verbose_name='最大库存')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '备件信息',
                'verbose_name_plural': '备件信息',
                'db_table': 'spare_part',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePartRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=20, verbose_name='记录类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('before_quantity', models.IntegerField(verbose_name='变动前库存')),
                ('after_quantity', models.IntegerField(verbose_name='变动后库存')),
                ('related_order_no', models.CharField(blank=True, max_length=50, verbose_name='关联单号')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='common.sparepart', verbose_name='备件')),
            ],
            options={
                'verbose_name': '备件记录',
                'verbose_name_plural': '备件记录',
                'db_table': 'spare_part_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='使用数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='repair.repairorder', verbose_name='工单')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_repairs', to='common.sparepart', verbose_name='备件')),
            ],
            options={
                'verbose_name': '维修备件使用',
                'verbose_name_plural': '维修备件使用',
                'db_table': 'repair_spare_part',
            },
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('operator_no', models.CharField(max_length=50, verbose_name='操作人账号')),
                ('operator_name', models.CharField(max_length=50, verbose_name='操作人姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='repair.repairorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '维修日志',
                'verbose_name_plural': '维修日志',
                'db_table': 'repair_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('workorder', '工单通知'), ('inspection', '巡检通知'), ('approval', '审批通知')], default='system', max_length=20, verbose_name='通知类型')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.repairstaff', verbose_name='接收维修人员')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
