# Generated by Django 4.2.29 on 2026-04-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='max_stock',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='supplier',
        ),
    ]
