# Generated by Django 4.2.29 on 2026-04-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_image_textfield'),
        ('common', '0004_remove_knowledgebase_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='category',
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipmenttype', verbose_name='设备类型'),
        ),
    ]
