# Generated by Django 4.2.29 on 2026-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_knowledgebase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='供货商'),
        ),
    ]
