# Generated by Django 4.2.29 on 2026-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_repairstaff_current_order_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Token')),
                ('user_type', models.CharField(choices=[('user', '用户'), ('staff', '维修人员'), ('admin', '管理员')], max_length=10, verbose_name='用户类型')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '认证令牌',
                'verbose_name_plural': '认证令牌',
                'db_table': 'auth_token',
            },
        ),
    ]
