# Generated by Django 4.2.29 on 2026-04-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-created_at'], 'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='repairstaff',
            options={'ordering': ['-created_at'], 'verbose_name': '维修人员', 'verbose_name_plural': '维修人员'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
