# Generated by Django 4.2.29 on 2026-05-06 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='留言标题')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='留言用户')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'db_table': 'message_board',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_deleted'], name='idx_msg_user'), models.Index(fields=['-created_at'], name='idx_msg_created')],
            },
        ),
    ]
